### ISSUE TITLE
Weird behavior in Umbraco 7.1.6

### ISSUE THREAD

**Issue by Medjeti** [kipusoep/UrlTracker#47]
Hiya,

I just installed the v3.2 package on a rather fresh Umbraco installation, but for some reason the redirects aren't working.

A few things are looking a bit weird:
* Deleted nodes are tracked and appear in the icUrlTracker table, but not in the list on the dashboard (not sure if this is the expected behavior).
* Renames are tracked and appear both in the table and the list, but the redirect never kicks in.
* Manual entries appear in the list and the table, but do not redirect.
* Nothing is logged in either the umbracoLog table nor the UmbracoTraceLog.txt file, even though urlTracker:enableLogging is set to true in the web.config.

I suspected it might have to do with having two different hostnames set on my frontpage node (not root node), but the issue remains even after removing one of the hostname.

Any idea what might be going on?

Thanks in advance!
/Mikael

**Comment by ryanology** [comment]
I'm running into the same situation as Medjeti just mentioned.  When I manually create a 301 redirect by entering the old URL in manually and then selecting the node to redirect to, it doesn't work - I just get a 404 page.  However, when I choose a previously tracked 404 page and then select the node to redirect to, that works.

The only difference in these scenarios is in the overview list: when I manually enter the old URL the "Site" column has a value of "Home" (NOTE: my home node but NOT the only root node - there is a configuration settings node also) but when I select a tracked 404 page that Site column does not have any value in it.

And on the redirect from the tracked 404 page, I can't view the Advanced Settings.  I just get a bunch of popup errors:
Sys.WebForms.PageRequestManagerServerException: 'ddlRootNode' has a SelectedValue which is invalid because it does not exist in the list of items.
Parameter name: value

Could that have something to do with not having a singular root node?  Is there a workaround?

Also, numerous favicon.ico URLs are getting tracked as 404 pages.  I can verify that the favicon is not getting loaded on every page, but I thought this plugin was not supposed to track it by default?

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by kipusoep** [comment]
No reply, so closing.
